project:
  type: website

website:
  title: ""
  repo-url: https://github.com/quarto-dev/quarto-demo
  search: false
  page-footer: 
    center: 
      - icon: github
        href: https://github.com/milanwiedemann
      - icon: mortarboard-fill
        href: https://scholar.google.co.uk/citations?user=MlR2ow4AAAAJ&hl=en
      - icon: mastodon
        href: https://fosstodon.org/@milanwiedemann
      - icon: twitter
        href: https://twitter.com/milanwiedemann
      - icon: linkedin
        href: https://www.linkedin.com/in/milanwiedemann/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV

format:
  html:
    theme: litera
    css: styles.css
    toc: true



