baseurl = "https://www.milanwiedemann.com/"
languageCode = "en-us"
title = "Milan Wiedemann"
theme = "hugo-ivy"
disqusShortname = "milanwiedemann"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2
    
[[menu.main]]
    name = "Presentations"
    url = "/presentations/"
    weight = 4
    
[[menu.main]]
    name = "Thesis"
    url = "https://ora.ox.ac.uk/objects/uuid:96ac1526-0405-4147-b071-2b3bb0e24802"
    weight = 4
    
[[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 5
    
[[menu.main]]
    name = "Videos"
    url = "/media/"
    weight = 6
    
[[menu.main]]
    name = "CV"
    url = "/cv/cv-milanwiedemann.pdf"
    weight = 7
  
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 8

[params]
    description = "Healthcare, Data Science, Experimental Psychology"
    footer = "&copy; [Milan Wiedemann](/) 2021 | [Twitter](https://twitter.com/milanwiedemann) | [Google Scholar](https://scholar.google.co.uk/citations?user=MlR2ow4AAAAJ&hl=en) | [GitHub](https://github.com/milanwiedemann) | [ORCID](https://orcid.org/0000-0003-1991-282X) | [OSF](https://osf.io/dycce)"
    
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  