---
title: Publications
disable_comments: true
---


My publications and further materials are listed below.
If you cant find or access the paper you're looking for [please let me know](/contact).

## Research Papers

### Peer-reviewed

- **Wiedemann, M.**, [Stott, R.](https://twitter.com/DrRichardStott), [Nickless, A.](https://twitter.com/Jancia36), [Beierl, E. T.](https://twitter.com/EBeierl), [Wild, J.](https://twitter.com/drjenwild), [Warnock-Parkes, E.](https://twitter.com/DrEmmaWParkes), [Grey, N.](https://twitter.com/nickdgrey?lang=en), [Clark, D. M.](https://www.psy.ox.ac.uk/team/david-clark), & [Ehlers A.](https://www.psy.ox.ac.uk/team/anke-ehlers) (2020).
  Cognitive processes associated with sudden gains in cognitive therapy for posttraumatic stress
disorder in routine care. *Journal of Consulting and Clinical Psychology*. doi: [10.1037/ccp0000488](https://psycnet.apa.org/fulltext/2020-15049-001.html). ([PDF](https://psycnet.apa.org/fulltext/2020-15049-001.pdf), [Code](https://osf.io/dgt8x/), [Supp](http://supp.apa.org/psycarticles/supplemental/ccp0000488/sg-ptsd-audit-jccp-supp-rev-3-v2.docx)).

- **Wiedemann, M.**, [Thew, G. R.](https://twitter.com/drgrahamthew), [Stott, R.](https://twitter.com/DrRichardStott), [Ehlers, A.](https://www.psy.ox.ac.uk/team/anke-ehlers) (2019). 
`suddengains`: An R package to identify sudden gains in longitudinal data. 
_PLOS ONE_.
doi: [10.1371/journal.pone.0230276](https://doi.org/10.1371/journal.pone.0230276). ([Postprint](https://psyarxiv.com/2wa84/download), [Website](https://milanwiedemann.github.io/suddengains/), [Code](https://github.com/milanwiedemann/suddengains)).

- [Košir, U.](https://twitter.com/UrskaKosir), [Loades, M. E.](https://twitter.com/MariaLoades), [Wild, J.](https://twitter.com/drjenwild), **Wiedemann, M.**, Krajnc, A., Roškar, S. & [Bowes, L.](https://twitter.com/DrLucyBowes) (2020). 
The Impact of COVID-19 on the Cancer Care of Adolescents and Young Adults and Their Well-Being: Results From an Online Survey Conducted in the Early Stages of the Pandemic
_Cancer_. 
doi: [10.1002/cncr.33098](https://acsjournals.onlinelibrary.wiley.com/doi/full/10.1002/cncr.33098).
([PDF](https://acsjournals.onlinelibrary.wiley.com/doi/epdf/10.1002/cncr.33098)).

- [Košir, U.](https://twitter.com/UrskaKosir), **Wiedemann, M.**, [Wild, J.](https://twitter.com/drjenwild), [Bowes, L.](https://twitter.com/DrLucyBowes) (2019). 
Cognitive Mechanisms in Adolescent and Young Adult Cancer Patients and Survivors: Feasibility and Preliminary Insights from the Cognitions and Affect in Cancer Resiliency Study. 
_Journal of Adolescent and Young Adult Oncology_. 
doi: [10.1089/jayao.2019.0127](https://www.liebertpub.com/doi/10.1089/jayao.2019.0127).
([PDF](https://www.liebertpub.com/doi/pdf/10.1089/jayao.2019.0127), [Postprint](https://psyarxiv.com/d3cjy/), [Code](https://osf.io/puk28/)).

- [Košir, U.](https://twitter.com/UrskaKosir), **Wiedemann, M.**, [Wild, J.](https://twitter.com/drjenwild), [Bowes, L.](https://twitter.com/DrLucyBowes) (2019). 
Psychiatric disorders in adolescent cancer survivors: A systematic review of prevalence and predictors. 
_Cancer Reports_. 
doi: [10.1002/cnr2.1168](https://onlinelibrary.wiley.com/doi/full/10.1002/cnr2.1168).
([PDF](https://onlinelibrary.wiley.com/doi/epdf/10.1002/cnr2.1168), [Video](https://youtu.be/4SBjIkFNAGQ)).

- [Wild, J.](https://twitter.com/drjenwild), [Warnock-Parkes, E.](https://twitter.com/EmmaWParkes), [Grey, N.](https://twitter.com/nickdgrey), [Stott, R.](https://twitter.com/DrRichardStott), **Wiedemann, M.**, … [Ehlers, A.](https://www.psy.ox.ac.uk/team/anke-ehlers) (2016). 
Internet-delivered cognitive therapy for PTSD: A development pilot series. 
_European Journal of Psychotraumatology_. 
doi: [10.3402/ejpt.v7.31019](https://www.tandfonline.com/doi/abs/10.3402/ejpt.v7.31019?needAccess=true#).
([PDF](https://www.tandfonline.com/doi/pdf/10.3402/ejpt.v7.31019?needAccess=true&)).

### Preprints

- [Lorenzo-Luaces, L.](https://twitter.com/lluaces), **Wiedemann, M.**, [Huibers, M.J.H.](https://research.vu.nl/en/persons/marcus-huibers), [Lemmens, L.H.J.M.](https://www.maastrichtuniversity.nl/lotte.lemmens) (2020). 
A permutation test to probe the statistical significance of sudden gain frequency: An application to patterns of change in cognitive and interpersonal therapy for depression.
_PsyArXiv_. 
doi: [10.31234/osf.io/jbzw3](https://psyarxiv.com/jbzw3).
([Code](https://osf.io/d7rg2/)).


## Presentations

- **Wiedemann, M.**. (2020, February).
  My journey from error messages to R Packages - Building tools to improve reproducibility and productivity in clinical psychology.
  *R User Group Oxford, UK*.
  ([Slides](https://github.com/r-oxford/r-oxford.github.io/blob/master/slides/2020_02_my_R_journey.pdf)).

- **Wiedemann, M.**, Janecka M., Wild J., Warnock-Parkes, E., Stott, R., Grey N., Clark D. M., & Ehlers A. (2019, July). 
  A test of theory-derived mediators of clinical improvement in cognitive therapy for PTSD.
  *World Congress of Behavioural and Cognitive Therapies, Berlin, Germany*.
  ([Programme](https://wcbct2019.org/Downloads/Congress-Programme.pdf)).

- **Wiedemann, M.**, Stott, R., Nickless, A., Beierl, E., Wild, J., Warnock-Parkes, E., Grey, N., Clark, D. M., & Ehlers A. (2019, July).
  Cognitive processes of sudden gains in cognitive therapy for PTSD in routine clinical care.
  *World Congress of Behavioural and Cognitive Therapies, Berlin, Germany*.
  ([Programme](https://wcbct2019.org/Downloads/Congress-Programme.pdf)).
  
- Wiedemann, M., **Thew, G. (Presenter)**, Stott, R. & Ehlers A. (2019, July).
  Automating the identification of sudden gains within psychological therapy datasets: A new R package.
  *World Congress of Behavioural and Cognitive Therapies, Berlin, Germany*.
  ([Poster](https://doi.org/10.6084/m9.figshare.11299289.v1)).

- **Wiedemann, M.** (2019, March). Tutorial on latent change score modeling in R: Combining the strengths of the packages *lavaan*, *broom*, and *semPlot*. *Berlin Oxford Training Alliance for Quantitative Neuroscience, Germany.* ([Poster](https://doi.org/10.6084/m9.figshare.7887599.v2)).

- **Wiedemann, M.**, Clark, D. M. & Ehlers, A. (2019, February). Taking a closer look at how therapy works. *Mental Health Research UK - Scholars' Day 2019, London, UK*. ([Slides](https://doi.org/10.6084/m9.figshare.7834841.v1)).
  
- **Wiedemann, M.**, Clark, D. M. & Ehlers, A. (2018, September). Processes of change in cognitive therapy for PTSD - Sudden symptom improvements during therapy. *University of Groningen, WEIRD Seminar Series, Netherlands.*

- **Wiedemann, M.**, Clark, D. M. & Ehlers, A. (2018, June). Sudden gains in cognitive therapy for PTSD - Can large and stable improvements between sessions help us understand how therapy works? *University of Exeter, Mood Disorder Centre, The Think-Tank Seminar, UK.* ([Slides](https://doi.org/10.6084/m9.figshare.7834844.v1)).

- **Wiedemann, M.**, Clark, D. M. & Ehlers, A. (2018, February). Processes of change in trauma-focused cognitive therapy for PTSD.  *Mental Health Research UK - Scholars' Day 2018, London, UK.* ([Slides](https://doi.org/10.6084/m9.figshare.7834826.v1)).
  
